### ISSUE TITLE
Not compatible with taskwarrior 3

### ISSUE THREAD

**Issue by timodenissen** [DCsunset/taskwarrior-webui#83]
Title says it all.

Since taskwarrior 3.0 requires a manual data migration into a sqlite3 database, taskwarrior-webui no longer works.

**Comment by Mebus** [comment]
Hey,

how can the migration be done?

Mebus

**Comment by timodenissen** [comment]
> how can the migration be done?

Following the official guide:

* With Taskwarrior 2: export all tasks to a `json` file: `task export > all-tasks.json`
* Upgrade to Taskwarrior 3
* With Taskwarrior 3: import all tasks: task import rc.hooks=0 all-tasks.json

Source: https://taskwarrior.org/docs/upgrade-3/

Running taskwarrior-webui creates an empty Taskwarrior 2 database, which Taskwarrior 3 then complains about (but still works, it just ignores the Taskwarrior 2 database files).

**Comment by phanimahesh** [comment]
To make the webui compatible, looks like the only changes needed are to install taskwarrior v3 instead of v2 in the docker image, assuming the user has migrated their tasks. However looks like everything in the frontend ecosystem has moved on, with many dependencies being out of date and some being deprecated, which prevents building the docker image now.

updating the dependencies and clean building a new docker image with v3 taskwarrior should be sufficient from my reading of the code.

**Comment by DCsunset** [comment]
I have updated taskwarrior command to v3 in the docker image `dcsunset/taskwarrior:3`. Can someone test this container to see if it works with their existing data?

**Comment by Mebus** [comment]
I don't see any tasks in the web-ui :-(

**Comment by timodenissen** [comment]
> I have updated taskwarrior command to v3 in the docker image `dcsunset/taskwarrior:3`. Can someone test this container to see if it works with their existing data? (Make sure you back up your data first)

Works for me with the latest tag `dcsunset/taskwarrior-webui:20240703` :)

Issue is resolved for me :)

**Comment by DCsunset** [comment]
@Mebus The new image only supports database in taskwarrior 3 format. Are you trying it with migrated data?

**Comment by phanimahesh** [comment]
Can confirm that the new image works. Thanks a lot!
