### ISSUE TITLE
CA certificate not found when trying to connect to taskd

### ISSUE THREAD

**Issue by GuiGui2** [DCsunset/taskwarrior-webui#9]
Thanks for work, this is exactly what I was looking for!
I'm trying to connect to my taskd.
I've confirmed taskwarrior can connect from the CLI and sync to the taskd:

```
[guigui@tasks ~]$ task sync
Syncing with 10.10.10.7:53589

Sync successful.  No changes.
```

I've mounted both ~/.task and ~/.taskrc into the container. Yet, when I try to sync, I get the following error in the logs: 
```
Server listening on http://0.0.0.0:3000
  <-- POST /sync
  xxx POST /sync 400 18ms -
TASKRC override: /.taskrc
TASKDATA override: /.task
Configuration override rc.confirmation:no
Configuration override rc.recurrence.confirmation:no
Configuration override rc.dependency.confirmation:no
Configuration override rc.json.depends.array:yes
Configuration override rc.bulk:0
CA certificate not found.
```

I've looked inside the container, the certs are there: 

```
[guigui@tasks ~]$ podman exec 34f06d8bd9d6 ls -al /.task
total 36
drwxrwxr-x    2 root     root           221 Mar 12 14:47 .
dr-xr-xr-x   22 root     root            34 Mar 12 14:50 ..
-rw-r--r--    1 root     root          2009 Mar 12 14:42 Guillaume_XXX.cert.pem
-rw-r--r--    1 root     root         10725 Mar 12 14:42 Guillaume_XXX.key.pem
-rw-r--r--    1 root     root          2009 Mar 12 10:38 Guillaume_WebUI.cert.pem
-rw-r--r--    1 root     root         10719 Mar 12 10:38 Guillaume_WebUI.key.pem
-rw-rw-r--    1 root     root             0 Mar 12 14:47 backlog.data
-rw-r--r--    1 root     root          2009 Mar 12 14:43 ca.cert.pem
-rw-rw-r--    1 root     root             0 Mar 12 14:47 completed.data
-rw-rw-r--    1 root     root             0 Mar 12 14:47 pending.data
```
On the host, it looks like that: 

```
[guigui@tasks ~]$ ls -al .task
total 36
drwxrwxr-x. 2 guigui guigui   221 Mar 12 14:47 .
drwx------. 7 guigui guigui   220 Mar 12 14:46 ..
-rw-rw-r--. 1 guigui guigui     0 Mar 12 14:47 backlog.data
-rw-r--r--. 1 guigui guigui  2009 Mar 12 14:43 ca.cert.pem
-rw-rw-r--. 1 guigui guigui     0 Mar 12 14:47 completed.data
-rw-r--r--. 1 guigui guigui  2009 Mar 12 14:42 Guillaume_XXX.cert.pem
-rw-r--r--. 1 guigui guigui 10725 Mar 12 14:42 Guillaume_XXX.key.pem
-rw-r--r--. 1 guigui guigui  2009 Mar 12 10:38 Guillaume_WebUI.cert.pem
-rw-r--r--. 1 guigui guigui 10719 Mar 12 10:38 Guillaume_WebUI.key.pem
-rw-rw-r--. 1 guigui guigui     0 Mar 12 14:47 pending.data
```
My taskrc looks like this: 

```
[guigui@tasks ~]$ cat .taskrc 
taskd.certificate=\/home\/guigui\/.task\/Guillaume_XXX.cert.pem
taskd.key=\/home\/guigui\/.task\/Guillaume_XXX.key.pem
taskd.ca=\/home\/guigui\/.task\/ca.cert.pem
taskd.server=10.10.10.7:53589
taskd.credentials=GuiGui2\/Guillaume XXX\/2bb188ed-5a1f-4e5e-be1c-d748ac6fccc9
taskd.trust=ignore hostname
```
Does taskwarrior-webui looks for a CA cert with a different name ?
Thanks for the help!

**Comment by DCsunset** [comment]
The error occurs because the paths of the certificates are specified in your `.taskrc`. So it couldn't find it because the certificates locate in `/.task` rather than `$HOME/.task`.

A quick solution is to mount `$HOME/.task` to the same directory in the container but it is not very intuitive.

Maybe I should add an environment variable like `ORIGINAL_TASK_DIR` to let the container create a symbolic link automatically?

**Comment by DCsunset** [comment]
The error occurs because the paths of the certificates are specified in your `.taskrc`. So it couldn't find it because the certificates locate in `/.task` rather than `$HOME/.task`.

A quick solution is to mount `$HOME/.task` to the same directory in the container but it is not very intuitive.

Maybe I should add an environment variable like `ORIGINAL_TASK_DIR` to let the container create a symbolic link automatically?

**Comment by GuiGui2** [comment]
Hi, sorry I forgot to report success.
Mapping $HOME/.task from the host into /.task in the container fixed issue. Thanks!
